### ISSUE TITLE
Literal `add_on: ["ddev/ddev-redis-commander"]` shouldn't be?

### ISSUE THREAD

**Issue by rfay** [ddev/github-action-add-on-test#14]
Isn't this wrong? The add_on value shouldn't be a literal like this should it?

```yaml
      matrix:
        ddev_version: [ stable, HEAD ]
        add_on: ["ddev/ddev-redis-commander"]
```

See https://github.com/ddev/github-action-add-on-test/blob/b27b22c2f2b45666036959e7a813c08a4b9e2028/.github/workflows/single-add-on-test.yml#L16-L22
