### ISSUE TITLE
Turn off instrumentation

### ISSUE THREAD

**Issue by tyler36** [ddev/github-action-add-on-test#24]
In the "2023-10-31 Amplitude Analytics" training session, @rfay pointed out (around 29:41) that `ddev drush` was being used alot and someone may have analytics turned on during testing.

We should confirm that by using this action, we are not unnessasarily contributing to analytics.

**Comment by tyler36** [comment]
I see we have the following set in `action.yaml`. Is that enough to prevent analytics for both the 'stable' and 'HEAD' versions of DDEV installed?

```
    - name: Run test
      env:
        # Don't send telemetry to amplitude
        DDEV_NO_INSTRUMENTATION: "true"
```
