### ISSUE TITLE
Move to ddev org and update add-on-template next

### ISSUE THREAD

**Issue by rfay** [ddev/github-action-add-on-test#8]
I'm giving this a try on https://github.com/ddev/ddev-beanstalkd and it seems to be perfect; please take a look and see if I've messed anything up. What a tremendous improvement!

Our next steps when you're ready will be to 
* Move to ddev org
* update the ddev-addon-template.

**Comment by julienloizelet** [comment]
Hi @rfay , thanks for testing.

[For this test](https://github.com/ddev/ddev-beanstalkd/blob/main/.github/workflows/tests.yml), I think you can remove :

```
defaults:
  run:
    shell: bash
```

and 

```
env:
  NIGHTLY_DDEV_PR_URL: "https://nightly.link/ddev/ddev/actions/runs/1720215802/ddev-linux-amd64.zip"
  # Allow ddev get to use a github token to prevent rate limiting by tests
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The `NIGHTLY_DDEV_PR_URL` feature is not implemented and the DDEV_GITHUB_TOKEN will be filled by the `token` input.


If you want to test the "keep alive" feature, you can add set the `keepalive_time_elapsed` input. It is 55 by default, but if you set 0, a dummy commit should be created on each run.

What should I do to move this repo to the ddev org ?

Thanks
